execute pathogen#infect()
syntax on

" Spaces are better than tabs :P
filetype plugin indent on
set tabstop=2
set shiftwidth=2
set expandtab

set t_Co=256
set laststatus=2
set number
let g:airline_powerline_fonts = 1
let g:airline_theme='murmur'
