execute pathogen#infect()
syntax on

" Spaces are better than tabs :P
filetype plugin indent on
set tabstop=2
set shiftwidth=2
set expandtab

set scrolloff=4

set t_Co=256
set laststatus=2
set number
let g:airline_powerline_fonts = 1
let g:airline_theme='murmur'

" markdown-preview
let vim_markdown_preview_toggle=1
let vim_markdown_preview_browser='Firefox'
let vim_markdown_preview_use_xdg_open=1
let vim_markdown_preview_github=1

" markdown-toc
let g:vmt_auto_update_on_save=0
let g:vmt_dont_insert_fence=1
let g:vmt_cycle_list_item_markers=1
